### PR TITLE
updated profile of eliya

### PR DESCRIPTION
**Pull request by eliyahabba**
A picture has been uploaded.
Adding details to the information page

### CODE REVIEW

**Comment by eliyahabba** [comment]
@gabrielStanovsky Please take a look

**Comment by gabrielStanovsky** [comment]
@eliyahabba Thanks!
This currently just adds the picture, right? Can you add a description to https://github.com/gabrielStanovsky/gabrielStanovsky.github.io/blob/master/_data/msc_students.yml ?

**Comment by eliyahabba** [comment]
@gabrielStanovsky  Done:)

**Comment by gabrielStanovsky** [comment]
Thanks! merging :)

**Pull request merged**
